name: Build and Deploy
on:
  schedule:
    - cron: '13 2 * 1-12 5'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ~> 2.7
      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec ruby templates/index.rb > public/index.html
      - name: archive public directory
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
